<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:macro name="base">

  <!-- ================= PROPERTIES ================= -->
  <xacro:property name="base_length" value="0.5"/>
  <xacro:property name="base_width" value="0.4"/>
  <xacro:property name="base_height" value="0.2"/>

  <xacro:property name="wheel_radius" value="0.075"/>
  <xacro:property name="wheel_width" value="0.04"/>

  <xacro:property name="wheel_x_offset" value="0.18"/>
  <xacro:property name="wheel_y_offset" value="0.22"/>

  <!-- ================= BASE LINK ================= -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2 + 0.05}"/>
      <material name="body_color">
        <color rgba="0.15 0.15 0.18 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2 + 0.05}"/>
    </collision>

    <inertial>
      <mass value="10.0"/>
      <origin xyz="0 0 ${base_height/2 + 0.05}"/>
      <inertia
        ixx="0.2"
        iyy="0.2"
        izz="0.2"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <gazebo reference="base_link">
    <self_collide>false</self_collide>
  </gazebo>

  <!-- ================= IMU LINK ================= -->
<link name="imu_link"/>

<joint name="imu_joint" type="fixed">
  <parent link="base_link"/>
  <child link="imu_link"/>
  <origin xyz="0 0 0.15"/>
</joint>

<gazebo reference="imu_link">
  <sensor name="imu_sensor" type="imu">
    <always_on>true</always_on>
    <update_rate>100</update_rate>
    <imu>
      <angular_velocity>
        <x>true</x>
        <y>true</y>
        <z>true</z>
      </angular_velocity>
      <linear_acceleration>
        <x>true</x>
        <y>true</y>
        <z>true</z>
      </linear_acceleration>
    </imu>
  </sensor>
</gazebo>

  <!-- ================= WHEEL MACRO ================= -->
  <xacro:macro name="wheel" params="name x y">

    <link name="${name}_link">
      <visual>
        <origin rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.05 0.05 0.05 1"/>
        </material>
      </visual>

      <collision>
        <origin rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <inertial>
        <mass value="1.0"/>
        <origin xyz="0 0 0"/>
        <inertia
          ixx="0.01"
          iyy="0.01"
          izz="0.005"
          ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} ${wheel_radius}"/>
      <axis xyz="0 1 0"/>
    </joint>

  </xacro:macro>

  <!-- ================= 4 WHEELS ================= -->

  <xacro:wheel name="front_left_wheel"
               x="${wheel_x_offset}"
               y="${wheel_y_offset}"/>

  <xacro:wheel name="rear_left_wheel"
               x="-${wheel_x_offset}"
               y="${wheel_y_offset}"/>

  <xacro:wheel name="front_right_wheel"
               x="${wheel_x_offset}"
               y="-${wheel_y_offset}"/>

  <xacro:wheel name="rear_right_wheel"
               x="-${wheel_x_offset}"
               y="-${wheel_y_offset}"/>

</xacro:macro>

</robot>